### ISSUE TITLE
Impossible to install

### ISSUE THREAD

**Issue by vikbez** [Zigazou/PyMinitel#3]
setup.py asks for package pybot-youpi,
but I can't find it anywhere

**Comment by Zigazou** [comment]
Hi ! I think you mistook PyMinitel with Youpinitel. For issues about Youpinitel, you need to go there [https://github.com/EricPobot/youpinitel-v1-raspi/issues](https://github.com/EricPobot/youpinitel-v1-raspi/issues)

**Comment by vikbez** [comment]
Thanks... sorry I'm tired :disappointed:
