### ISSUE TITLE
Impossible de désactiver l'écho local en mode téléinformatique

### ISSUE THREAD

**Issue by paullouisageneau** [Zigazou/PyMinitel#4]
Bonjour, après quelques tests avec cette excellente bibliothèque, il semble qu'il soit impossible de désactiver l'écho local après avoir basculé en mode téléinformatique sur Minitel 1B. Sauriez-vous si c'est un comportement normal, ou un bug ? Dans les modes videotex et mixte, la commande fonctionne comme attendu.

Le code suivant présente ce comportement : 
`minitel = Minitel(peripherique = '/dev/ttyUSB0')`
`minitel.identifier()`
`minitel.definir_vitesse(4800)`
`minitel.definir_mode('TELEINFORMATIQUE')`
`minitel.echo(False) # N'a aucun effet`

**Comment by Zigazou** [comment]
Hello !

Il s’agit visiblement d’un oubli. Et donc d’un bug ;-)

La méthode echo ([du fichier Minitel.py](https://github.com/Zigazou/PyMinitel/blob/master/minitel/Minitel.py#L874)) envoie directement une commande PROTOCOL mais il se trouve qu’en mode TELEINFORMATIQUE, le Minitel n’interprète pas les commandes PROTOCOL, uniquement les commandes CSI.

Peux-tu essayer `minitel.envoyer([CSI, "12h"])` ? (il faut que je rebranche un Minitel, tu devrais donc y arriver plus vite que moi :o) )

@+

**Comment by paullouisageneau** [comment]
D'accord, je vois le problème ! 

J'ai essayé `minitel.envoyer([CSI, "12h"])`, malheureusement le code d'échappement n'a aucun effet, en tout cas sur minitel 1B. Peut-être qu'il n'est pas implémenté, ou que le minitel en utilise un autre ? Il serait plutôt étrange que cette fonction n'existe pas.

**Comment by paullouisageneau** [comment]
Hello, après quelques essais, il semble que la commande ne soit pas disponible sur le Minitel 1, mais elle semble l'être sur le Minitel 2, ce qui confirme la spécification ici: http://millevaches.hydraule.org/info/minitel/specs/

**Comment by paullouisageneau** [comment]
Je ferme, la commande n'est pas disponible sur le Minitel 1.
