### ISSUE TITLE
Structure pour une navigation entre pages?

### ISSUE THREAD

**Issue by t0mg** [Zigazou/PyMinitel#6]
Hello,

avec ma maigre expérience de python et sans pouvoir générer la doc (#5) je galère un peu à comprendre comment créer un service permettant de naviguer entre plusieurs "pages" (écrans) via un menu (ou un champ texte avec un code). Pourrais-tu m'expliquer la structure de base nécessaire pour mettre en place un tel système?

Merci!

**Comment by Zigazou** [comment]
Hello !

Comme PyMinitel est une librairie et non un framework, elle ne fournit pas de cadre standard pour la constitution d’un serveur Minitel.

Néanmoins, une boucle classique ressemble à ceci : 

    from minitel.Minitel import Minitel

    minitel = Minitel()

    minitel.deviner_vitesse()
    minitel.identifier()
    # minitel.definir_mode('VIDEOTEX')
    # minitel.configurer_clavier(etendu = True, curseur = False, minuscule = True)
    # minitel.echo(False)
    # minitel.efface()
    # minitel.curseur(False)

    while True:
        try:
            r = minitel.recevoir_sequence(attente=30)
            # r contient la séquence envoyée par le Minitel qu'il faut désormais traiter
        except Empty :
            pass

Les séquences envoyées par le Minitel varient en fonction de la touche appuyée, évidemment, mais aussi du mode en cours du Minitel (surtout valable pour les touches spéciales  comme les touches fléchées). On parle bien de séquences car les lettres accentuées ou les touches spéciales génère plusieurs caractères.

Pour avoir un exemple de traitement des séquences des touches, tu peux regarder la méthode gere_touche du fichier minitel/UI/ChampTexte.py

Pour l’envoi de la page, la méthode envoyer de Minitel fait exactement ce à quoi on s’attend :-)

Pour la création de pages, tu peux utiliser Minitel Page Editor https://zigazou.github.io/miedit . C’est la technique qui était utilisée : on créait un fond avec un éditeur et les éventuelles modifications venaient se rajouter par-dessus.

**Comment by t0mg** [comment]
Ok donc en gros il faut réécrire la méthode exécuter de UI, et sortir de la boucle pour aller vers une nouvelle page lorsque la séquence correspond à ce que l'on attend (par exemple numéro + envoi). En gros, il faut que je remplace executer() par un truc du genre attendre(condition de sortie).

J'ai déjà testé miedit aussi, bravo il y a du boulot! Les curseurs svg ne fonctionnent pas sous Chrome par contre si je me souviens bien. Effectivement mon idée était de créer quelques pages avec cet outil et de faire une logique de navigation basique avec PyMinitel pour pouvoir passer de l'une à l'autre (pour faire un genre de kiosque).

**Comment by Zigazou** [comment]
Tu n'y es pas obligé. Les classes de UI ont été conçues dans l'optique de créer une interface utilisateur un peu évoluée (gestion du focus etc.). Dans ton cas, c’est superflu.

Oui, j’ai effectivement le problème des curseurs SVG pour Chrome avec Miedit ;-)

Le plus simple, à mon avis, est de créer une arborescence de fichiers avec des répertoires. Dans chaque répertoire, tu places un fichier command.lst (par exemple) et un fichier index.vdt. index.vdt est le fichier par défaut du répertoire et command.lst contient une liste de couples touche/fichier indiquant l’action à réaliser lire en fonction de la touche appuyée.

**Comment by t0mg** [comment]
Oui ça me semble le plus simple effectivement, j'essaierai d'aller dans cette direction une fois que j'aurai un test de base qui fonctionne :) Les fichiers vdt peuvent être utilisés directement avec Minitel.envoyer() ?

**Comment by Zigazou** [comment]
Normalement, oui. Les fichiers vdt sont des fichiers purement ASCII (7 bits), ils devraient donc passer les filtres de la classe Sequence.

**Comment by t0mg** [comment]
Je confirme, ça marche nickel :) Merci pour ton aide, j'ai maintenant un truc de base qui fonctionne.

Je rencontre quelques petits soucis mineurs avec miedit (canvas trop grand dans l'éditeur de graphique qui empêche d'accéder à la barre d'outils, manque les curseurs sour Chrome), et un plus gênant qui est l'impossibilité d'exporter les pages, j'ai donc ouvert [un ticket à ce sujet ici](https://github.com/Zigazou/miedit/issues/4).
